### ISSUE TITLE
Geomean error, geomean of data from a group of papers.

### ISSUE THREAD

**Issue by KaimingTao** [hivdb/chiro-frontend#57]
<img width="1266" alt="Screen Shot 2022-02-04 at 17 52 52" src="https://user-images.githubusercontent.com/988193/152624303-08b0b49e-0ff3-4ecc-a4f8-e772e88b98d9.png">

Please see the second row, the Geomean is "<85". When using the individual data, the geomean is about "<12".

**Comment by philiptzou** [comment]
The `5.7` is changed to `<100` is because of https://github.com/hivdb/chiro-frontend/blob/master/src/views/search-drdb/tables/column-defs/agg-funcs.js#L204-L209:

When there are non-neutralized results, the algorithm currently takes the highest ineffective titer (for NT50) to replace the actual geomean titer and mark the geomean result as "ineffective".

I'm going to change this behavior to also using geomean to determine the "representative" of ineffective titers.
